# Generated by Django 5.1.4 on 2024-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
